In [1]:
from belgicapress import *
import time

#pd.set_option('display.max_rows', None) #pour visualiser toutes les lignes des dataframes, pas si gros dans ce cas-ci

In [2]:
annot = pd.read_csv(r'06_QueriesByVisit_towork2.csv', encoding="utf-8", engine="c", index_col="unique_id")

annot = annot.drop("query_tokens", axis=1)
annot = annot.rename(columns={'query_normalised': 'queries'})
annot.head()

           visitID  Column                             queries
unique_id
0-649635    649635       0                      london diamond
1-649635    649635       1              london diamond-workers
2-649635    649635       2  london diamond-workers trade union
3-649756    649756       3                            bioscope
4-649756    649756       4                              cinéma

In [3]:
prenoms = pd.read_csv(r"C:\Users\Boulot\Desktop\BelgicaPress\prenoms.tsv", encoding="utf8")
prenoms = set([str(name).strip().lower() for name in prenoms.prenoms])

In [4]:
noms_famille = pd.read_csv(r"C:\Users\Boulot\Desktop\BelgicaPress\Names.csv", encoding="utf8", error_bad_lines=False)
noms_famille = set([name.strip().lower() for name in noms_famille.names])

b'Skipping line 3228: expected 1 fields, saw 2\nSkipping line 3569: expected 1 fields, saw 4\nSkipping line 5837: expected 1 fields, saw 2\nSkipping line 7827: expected 1 fields, saw 2\nSkipping line 8024: expected 1 fields, saw 2\nSkipping line 21500: expected 1 fields, saw 2\nSkipping line 24299: expected 1 fields, saw 2\nSkipping line 24522: expected 1 fields, saw 2\nSkipping line 33830: expected 1 fields, saw 2\nSkipping line 35900: expected 1 fields, saw 2\nSkipping line 37354: expected 1 fields, saw 2\nSkipping line 37606: expected 1 fields, saw 2\nSkipping line 39436: expected 1 fields, saw 2\nSkipping line 39458: expected 1 fields, saw 2\nSkipping line 40315: expected 1 fields, saw 2\nSkipping line 41123: expected 1 fields, saw 2\nSkipping line 43831: expected 1 fields, saw 2\nSkipping line 48327: expected 1 fields, saw 2\nSkipping line 50428: expected 1 fields, saw 2\nSkipping line 51721: expected 1 fields, saw 2\nSkipping line 54022: expected 1 fields, saw 2\nSkipping line 54241: expected 1 fields, saw 2\nSkipping line 59653: expected 1 fields, saw 2\nSkipping line 59715: expected 1 fields, saw 2\nSkipping line 61716: expected 1 fields, saw 2\nSkipping line 65140: expected 1 fields, saw 2\nSkipping line 68379: expected 1 fields, saw 2\nSkipping line 70278: expected 1 fields, saw 2\nSkipping line 70954: expected 1 fields, saw 2\nSkipping line 74319: expected 1 fields, saw 2\nSkipping line 74402: expected 1 fields, saw 2\nSkipping line 75902: expected 1 fields, saw 2\nSkipping line 79779: expected 1 fields, saw 2\nSkipping line 82995: expected 1 fields, saw 2\nSkipping line 85910: expected 1 fields, saw 2\nSkipping line 85918: expected 1 fields, saw 2\nSkipping line 87530: expected 1 fields, saw 2\nSkipping line 89562: expected 1 fields, saw 2\nSkipping line 95480: expected 1 fields, saw 2\nSkipping line 96507: expected 1 fields, saw 2\nSkipping line 96892: expected 1 fields, saw 2\nSkipping line 96893: expected 1 fields, saw 2\nSkipping line 97589: expected 1 fields, saw 2\nSkipping line 97634: expected 1 fields, saw 2\nSkipping line 99986: expected 1 fields, saw 2\nSkipping line 102010: expected 1 fields, saw 2\nSkipping line 102343: expected 1 fields, saw 2\nSkipping line 104643: expected 1 fields, saw 2\nSkipping line 112210: expected 1 fields, saw 2\nSkipping line 113092: expected 1 fields, saw 2\nSkipping line 114170: expected 1 fields, saw 2\nSkipping line 114204: expected 1 fields, saw 2\nSkipping line 114212: expected 1 fields, saw 2\nSkipping line 116484: expected 1 fields, saw 2\nSkipping line 117367: expected 1 fields, saw 2\nSkipping line 122026: expected 1 fields, saw 2\nSkipping line 123118: expected 1 fields, saw 2\nSkipping line 124156: expected 1 fields, saw 2\nSkipping line 124334: expected 1 fields, saw 2\nSkipping line 124389: expected 1 fields, saw 2\nSkipping line 126230: expected 1 fields, saw 2\nSkipping line 126373: expected 1 fields, saw 2\nSkipping line 126880: expected 1 fields, saw 2\nSkipping line 126973: expected 1 fields, saw 2\nSkipping line 127096: expected 1 fields, saw 2\nSkipping line 130810: expected 1 fields, saw 2\nSkipping line 134304: expected 1 fields, saw 2\nSkipping line 142021: expected 1 fields, saw 2\nSkipping line 142154: expected 1 fields, saw 2\nSkipping line 142487: expected 1 fields, saw 2\nSkipping line 142959: expected 1 fields, saw 2\nSkipping line 143538: expected 1 fields, saw 2\nSkipping line 145431: expected 1 fields, saw 2\nSkipping line 146039: expected 1 fields, saw 2\nSkipping line 146576: expected 1 fields, saw 2\nSkipping line 146600: expected 1 fields, saw 2\nSkipping line 146615: expected 1 fields, saw 2\nSkipping line 148551: expected 1 fields, saw 2\nSkipping line 149457: expected 1 fields, saw 2\nSkipping line 149647: expected 1 fields, saw 2\nSkipping line 150274: expected 1 fields, saw 2\nSkipping line 152076: expected 1 fields, saw 2\nSkipping line 152077: expected 1 fields, saw 2\nSkipping line 158529: expected 1 fields, saw 2\nSkipping line 161650: expected 1 fields, saw 2\nSkipping line 161900: expected 1 fields, saw 2\nSkipping line 161970: expected 1 fields, saw 2\nSkipping line 161971: expected 1 fields, saw 2\nSkipping line 161972: expected 1 fields, saw 2\nSkipping line 163472: expected 1 fields, saw 2\nSkipping line 164685: expected 1 fields, saw 2\nSkipping line 165594: expected 1 fields, saw 2\nSkipping line 166790: expected 1 fields, saw 2\nSkipping line 169332: expected 1 fields, saw 2\nSkipping line 169417: expected 1 fields, saw 2\nSkipping line 170512: expected 1 fields, saw 2\nSkipping line 170522: expected 1 fields, saw 2\nSkipping line 172613: expected 1 fields, saw 2\nSkipping line 172616: expected 1 fields, saw 2\nSkipping line 172625: expected 1 fields, saw 2\nSkipping line 173202: expected 1 fields, saw 2\nSkipping line 173982: expected 1 fields, saw 3\nSkipping line 174156: expected 1 fields, saw 2\nSkipping line 174502: expected 1 fields, saw 2\nSkipping line 174579: expected 1 fields, saw 2\nSkipping line 180879: expected 1 fields, saw 2\nSkipping line 180997: expected 1 fields, saw 2\nSkipping line 181802: expected 1 fields, saw 2\nSkipping line 182143: expected 1 fields, saw 2\nSkipping line 183004: expected 1 fields, saw 2\nSkipping line 185052: expected 1 fields, saw 2\nSkipping line 185079: expected 1 fields, saw 2\nSkipping line 185552: expected 1 fields, saw 2\nSkipping line 185553: expected 1 fields, saw 2\nSkipping line 190101: expected 1 fields, saw 2\nSkipping line 191981: expected 1 fields, saw 2\nSkipping line 192495: expected 1 fields, saw 2\nSkipping line 195346: expected 1 fields, saw 2\nSkipping line 196065: expected 1 fields, saw 2\nSkipping line 198311: expected 1 fields, saw 2\nSkipping line 199443: expected 1 fields, saw 2\nSkipping line 199877: expected 1 fields, saw 2\nSkipping line 200268: expected 1 fields, saw 2\nSkipping line 201149: expected 1 fields, saw 2\nSkipping line 207211: expected 1 fields, saw 2\nSkipping line 207631: expected 1 fields, saw 2\nSkipping line 208562: expected 1 fields, saw 2\nSkipping line 211074: expected 1 fields, saw 2\nSkipping line 212591: expected 1 fields, saw 2\nSkipping line 213640: expected 1 fields, saw 2\nSkipping line 214457: expected 1 fields, saw 2\nSkipping line 215503: expected 1 fields, saw 2\nSkipping line 215504: expected 1 fields, saw 2\nSkipping line 215515: expected 1 fields, saw 2\nSkipping line 216698: expected 1 fields, saw 2\nSkipping line 217225: expected 1 fields, saw 2\nSkipping line 217231: expected 1 fields, saw 2\nSkipping line 217232: expected 1 fields, saw 2\nSkipping line 217233: expected 1 fields, saw 2\nSkipping line 218218: expected 1 fields, saw 2\nSkipping line 218221: expected 1 fields, saw 2\nSkipping line 225871: expected 1 fields, saw 2\nSkipping line 227734: expected 1 fields, saw 2\nSkipping line 229244: expected 1 fields, saw 2\nSkipping line 236340: expected 1 fields, saw 2\nSkipping line 236928: expected 1 fields, saw 2\nSkipping line 239382: expected 1 fields, saw 2\nSkipping line 240712: expected 1 fields, saw 2\nSkipping line 241229: expected 1 fields, saw 2\nSkipping line 242230: expected 1 fields, saw 2\nSkipping line 242457: expected 1 fields, saw 2\nSkipping line 243910: expected 1 fields, saw 2\nSkipping line 244688: expected 1 fields, saw 2\nSkipping line 245757: expected 1 fields, saw 2\nSkipping line 247987: expected 1 fields, saw 2\nSkipping line 250511: expected 1 fields, saw 2\nSkipping line 250655: expected 1 fields, saw 2\nSkipping line 251424: expected 1 fields, saw 2\nSkipping line 251824: expected 1 fields, saw 2\nSkipping line 252842: expected 1 fields, saw 2\nSkipping line 253277: expected 1 fields, saw 2\nSkipping line 258196: expected 1 fields, saw 2\nSkipping line 259674: expected 1 fields, saw 2\nSkipping line 259675: expected 1 fields, saw 2\nSkipping line 262291: expected 1 fields, saw 2\nSkipping line 262292: expected 1 fields, saw 2\nSkipping line 263148: expected 1 fields, saw 3\nSkipping line 263149: expected 1 fields, saw 2\nSkipping line 263150: expected 1 fields, saw 2\nSkipping line 264601: expected 1 fields, saw 2\nSkipping line 265820: expected 1 fields, saw 2\nSkipping line 266008: expected 1 fields, saw 2\nSkipping line 266030: expected 1 fields, saw 2\nSkipping line 267644: expected 1 fields, saw 2\nSkipping line 267885: expected 1 fields, saw 2\nSkipping line 268670: expected 1 fields, saw 2\nSkipping line 278213: expected 1 fields, saw 2\nSkipping line 278277: expected 1 fields, saw 2\nSkipping line 280321: expected 1 fields, saw 2\nSkipping line 281276: expected 1 fields, saw 2\nSkipping line 282427: expected 1 fields, saw 2\nSkipping line 283766: expected 1 fields, saw 2\nSkipping line 285091: expected 1 fields, saw 2\nSkipping line 286225: expected 1 fields, saw 2\nSkipping line 287897: expected 1 fields, saw 2\nSkipping line 293436: expected 1 fields, saw 2\nSkipping line 295697: expected 1 fields, saw 2\nSkipping line 296082: expected 1 fields, saw 2\nSkipping line 296124: expected 1 fields, saw 2\nSkipping line 297286: expected 1 fields, saw 2\nSkipping line 297781: expected 1 fields, saw 2\nSkipping line 298169: expected 1 fields, saw 2\nSkipping line 300335: expected 1 fields, saw 2\nSkipping line 300564: expected 1 fields, saw 2\nSkipping line 303039: expected 1 fields, saw 2\nSkipping line 304190: expected 1 fields, saw 2\nSkipping line 305227: expected 1 fields, saw 2\nSkipping line 306171: expected 1 fields, saw 2\nSkipping line 308086: expected 1 fields, saw 2\nSkipping line 308512: expected 1 fields, saw 2\nSkipping line 309199: expected 1 fields, saw 2\nSkipping line 315355: expected 1 fields, saw 2\nSkipping line 323798: expected 1 fields, saw 2\nSkipping line 325234: expected 1 fields, saw 2\nSkipping line 325540: expected 1 fields, saw 2\nSkipping line 326060: expected 1 fields, saw 2\nSkipping line 328948: expected 1 fields, saw 2\nSkipping line 332249: expected 1 fields, saw 2\nSkipping line 334637: expected 1 fields, saw 2\nSkipping line 337086: expected 1 fields, saw 2\nSkipping line 337664: expected 1 fields, saw 2\nSkipping line 340753: expected 1 fields, saw 2\nSkipping line 341864: expected 1 fields, saw 2\nSkipping line 344491: expected 1 fields, saw 2\nSkipping line 347293: expected 1 fields, saw 2\nSkipping line 347433: expected 1 fields, saw 2\nSkipping line 349694: expected 1 fields, saw 2\nSkipping line 350174: expected 1 fields, saw 2\nSkipping line 350524: expected 1 fields, saw 2\nSkipping line 352250: expected 1 fields, saw 2\nSkipping line 352264: expected 1 fields, saw 2\nSkipping line 354554: expected 1 fields, saw 2\nSkipping line 359995: expected 1 fields, saw 2\nSkipping line 360226: expected 1 fields, saw 2\nSkipping line 363648: expected 1 fields, saw 2\nSkipping line 364451: expected 1 fields, saw 2\nSkipping line 364573: expected 1 fields, saw 2\nSkipping line 367676: expected 1 fields, saw 2\nSkipping line 370419: expected 1 fields, saw 2\nSkipping line 370662: expected 1 fields, saw 2\nSkipping line 370956: expected 1 fields, saw 2\nSkipping line 372317: expected 1 fields, saw 2\nSkipping line 372534: expected 1 fields, saw 2\nSkipping line 372626: expected 1 fields, saw 2\nSkipping line 372649: expected 1 fields, saw 2\nSkipping line 373052: expected 1 fields, saw 2\nSkipping line 374704: expected 1 fields, saw 2\nSkipping line 375654: expected 1 fields, saw 2\nSkipping line 376201: expected 1 fields, saw 2\nSkipping line 378737: expected 1 fields, saw 2\nSkipping line 378946: expected 1 fields, saw 2\nSkipping line 383572: expected 1 fields, saw 2\nSkipping line 386514: expected 1 fields, saw 2\nSkipping line 387560: expected 1 fields, saw 2\nSkipping line 388049: expected 1 fields, saw 2\nSkipping line 388417: expected 1 fields, saw 2\nSkipping line 389002: expected 1 fields, saw 2\nSkipping line 389060: expected 1 fields, saw 2\nSkipping line 389326: expected 1 fields, saw 2\nSkipping line 390127: expected 1 fields, saw 2\nSkipping line 391000: expected 1 fields, saw 2\nSkipping line 392856: expected 1 fields, saw 2\nSkipping line 394829: expected 1 fields, saw 2\nSkipping line 396827: expected 1 fields, saw 2\nSkipping line 397875: expected 1 fields, saw 2\nSkipping line 401113: expected 1 fields, saw 2\nSkipping line 402582: expected 1 fields, saw 2\nSkipping line 404169: expected 1 fields, saw 2\nSkipping line 404221: expected 1 fields, saw 2\nSkipping line 404782: expected 1 fields, saw 2\nSkipping line 404845: expected 1 fields, saw 2\nSkipping line 404869: expected 1 fields, saw 2\nSkipping line 407180: expected 1 fields, saw 2\nSkipping line 407415: expected 1 fields, saw 2\nSkipping line 409147: expected 1 fields, saw 2\nSkipping line 409153: expected 1 fields, saw 2\nSkipping line 409212: expected 1 fields, saw 2\nSkipping line 409747: expected 1 fields, saw 2\nSkipping line 410078: expected 1 fields, saw 2\nSkipping line 411208: expected 1 fields, saw 2\nSkipping line 412252: expected 1 fields, saw 2\nSkipping line 414381: expected 1 fields, saw 2\nSkipping line 414574: expected 1 fields, saw 2\nSkipping line 414784: expected 1 fields, saw 2\nSkipping line 415010: expected 1 fields, saw 2\nSkipping line 415368: expected 1 fields, saw 2\nSkipping line 417686: expected 1 fields, saw 2\nSkipping line 417772: expected 1 fields, saw 2\nSkipping line 418951: expected 1 fields, saw 2\nSkipping line 419657: expected 1 fields, saw 2\nSkipping line 420579: expected 1 fields, saw 2\nSkipping line 421482: expected 1 fields, saw 2\nSkipping line 422179: expected 1 fields, saw 2\nSkipping line 422204: expected 1 fields, saw 2\nSkipping line 422205: expected 1 fields, saw 2\nSkipping line 422315: expected 1 fields, saw 2\nSkipping line 422615: expected 1 fields, saw 2\nSkipping line 423353: expected 1 fields, saw 2\nSkipping line 425366: expected 1 fields, saw 2\nSkipping line 426070: expected 1 fields, saw 2\nSkipping line 426700: expected 1 fields, saw 2\nSkipping line 426961: expected 1 fields, saw 2\nSkipping line 427288: expected 1 fields, saw 2\nSkipping line 427350: expected 1 fields, saw 2\nSkipping line 427518: expected 1 fields, saw 2\nSkipping line 431208: expected 1 fields, saw 2\nSkipping line 431741: expected 1 fields, saw 2\nSkipping line 432782: expected 1 fields, saw 2\nSkipping line 433064: expected 1 fields, saw 2\nSkipping line 433639: expected 1 fields, saw 2\nSkipping line 433751: expected 1 fields, saw 2\nSkipping line 435387: expected 1 fields, saw 2\nSkipping line 435801: expected 1 fields, saw 2\nSkipping line 436633: expected 1 fields, saw 2\nSkipping line 436704: expected 1 fields, saw 2\nSkipping line 438858: expected 1 fields, saw 2\nSkipping line 441548: expected 1 fields, saw 2\nSkipping line 444195: expected 1 fields, saw 2\nSkipping line 448650: expected 1 fields, saw 2\nSkipping line 448938: expected 1 fields, saw 2\nSkipping line 453076: expected 1 fields, saw 2\nSkipping line 454438: expected 1 fields, saw 2\nSkipping line 456600: expected 1 fields, saw 2\nSkipping line 457239: expected 1 fields, saw 2\nSkipping line 459557: expected 1 fields, saw 2\nSkipping line 462955: expected 1 fields, saw 2\nSkipping line 468065: expected 1 fields, saw 2\nSkipping line 468586: expected 1 fields, saw 2\nSkipping line 470187: expected 1 fields, saw 2\nSkipping line 474822: expected 1 fields, saw 2\nSkipping line 477868: expected 1 fields, saw 2\nSkipping line 482614: expected 1 fields, saw 2\nSkipping line 484165: expected 1 fields, saw 2\nSkipping line 484296: expected 1 fields, saw 2\nSkipping line 484453: expected 1 fields, saw 2\nSkipping line 484485: expected 1 fields, saw 2\nSkipping line 485501: expected 1 fields, saw 2\nSkipping line 487363: expected 1 fields, saw 2\nSkipping line 490113: expected 1 fields, saw 2\nSkipping line 490486: expected 1 fields, saw 2\nSkipping line 491966: expected 1 fields, saw 2\nSkipping line 492923: expected 1 fields, saw 2\nSkipping line 495289: expected 1 fields, saw 2\nSkipping line 496035: expected 1 fields, saw 2\nSkipping line 498415: expected 1 fields, saw 2\nSkipping line 501443: expected 1 fields, saw 2\nSkipping line 501444: expected 1 fields, saw 2\nSkipping line 501667: expected 1 fields, saw 2\nSkipping line 501693: expected 1 fields, saw 2\nSkipping line 501740: expected 1 fields, saw 2\nSkipping line 502074: expected 1 fields, saw 2\nSkipping line 502155: expected 1 fields, saw 2\nSkipping line 502156: expected 1 fields, saw 2\nSkipping line 503252: expected 1 fields, saw 2\nSkipping line 503907: expected 1 fields, saw 2\nSkipping line 504185: expected 1 fields, saw 2\nSkipping line 505298: expected 1 fields, saw 2\nSkipping line 505596: expected 1 fields, saw 2\nSkipping line 505639: expected 1 fields, saw 2\nSkipping line 508426: expected 1 fields, saw 2\nSkipping line 509908: expected 1 fields, saw 2\nSkipping line 510262: expected 1 fields, saw 2\nSkipping line 510415: expected 1 fields, saw 2\nSkipping line 510477: expected 1 fields, saw 2\nSkipping line 511161: expected 1 fields, saw 2\nSkipping line 511238: expected 1 fields, saw 2\nSkipping line 511520: expected 1 fields, saw 2\nSkipping line 511746: expected 1 fields, saw 2\nSkipping line 512142: expected 1 fields, saw 2\nSkipping line 512777: expected 1 fields, saw 2\nSkipping line 513291: expected 1 fields, saw 2\nSkipping line 513358: expected 1 fields, saw 2\nSkipping line 513497: expected 1 fields, saw 2\nSkipping line 513661: expected 1 fields, saw 2\nSkipping line 514835: expected 1 fields, saw 2\nSkipping line 514956: expected 1 fields, saw 2\nSkipping line 515159: expected 1 fields, saw 2\nSkipping line 515224: expected 1 fields, saw 2\nSkipping line 515438: expected 1 fields, saw 2\nSkipping line 517393: expected 1 fields, saw 2\nSkipping line 517596: expected 1 fields, saw 2\nSkipping line 520362: expected 1 fields, saw 2\nSkipping line 521189: expected 1 fields, saw 2\nSkipping line 523411: expected 1 fields, saw 2\nSkipping line 523538: expected 1 fields, saw 5\nSkipping line 524574: expected 1 fields, saw 2\n'

In [5]:
communes_complet = pd.read_csv(r"C:\Users\Boulot\Desktop\BelgicaPress\communes_et_sections.csv", encoding="utf8")

In [6]:
liste_mots = pd.read_csv(r"C:\Users\Boulot\Desktop\BelgicaPress\liste_mots.tsv", encoding="utf8")
liste_mots = set([name.strip().lower() for name in liste_mots.mots])

In [7]:
geo = pd.read_csv(r"C:\Users\Boulot\Desktop\BelgicaPress\communes_et_sections_noms_unifies.csv", encoding="utf8")
geo = geo.drop_duplicates(['noms_unifie'])
geo['lower'] = geo['noms_unifie'].str.lower()
lieux_be = set([str(name).strip() for name in geo.lower])

In [8]:
annot["extract_lieux_be"] = annot['queries'].apply(lambda x: get_lieux_clean(x, lieux_be, prenoms))
annot.head()

,visitID,Column,queries,extract_lieux_be
unique_id,,,,
0-649635,649635,0,london diamond,
1-649635,649635,1,london diamond-workers,
2-649635,649635,2,london diamond-workers trade union,
3-649756,649756,3,bioscope,
4-649756,649756,4,cinéma,

In [9]:
annot = tidy_split(annot, 'extract_lieux_be', sep='||')
annot

,visitID,Column,queries,extract_lieux_be
unique_id,,,,
0-649635,649635,0,london diamond,
1-649635,649635,1,london diamond-workers,
2-649635,649635,2,london diamond-workers trade union,
3-649756,649756,3,bioscope,
4-649756,649756,4,cinéma,
5-649756,649756,5,cinématographe,
6-649756,649756,6,cinématographie,
7-649756,649756,7,cinématographique,
8-649858,649858,8,soucoupes volantes,
9-649940,649940,9,delbecq guignies,guignies
10-649981,649981,10,cambron,
11-649981,649981,11,coinne,
12-649981,649981,12,coisne,
13-649981,649981,13,pruvost,
14-650099,650099,14,dendermonde,dendermonde
15-650298,650298,15,dendermonde,dendermonde
16-650480,650480,16,oud-strijder,
17-650574,650574,17,assenede bassevelde boekhoute bouchaute oost-e...,bassevelde
17-650574,650574,17,assenede bassevelde boekhoute bouchaute oost-e...,boekhoute
17-650574,650574,17,assenede bassevelde boekhoute bouchaute oost-e...,oost-eecloo
17-650574,650574,17,assenede bassevelde boekhoute bouchaute oost-e...,assenede
18-650574,650574,18,assenede bassevelde bouchaute boekhoute oost-e...,bassevelde
18-650574,650574,18,assenede bassevelde bouchaute boekhoute oost-e...,boekhoute
18-650574,650574,18,assenede bassevelde bouchaute boekhoute oost-e...,oost-eecloo
18-650574,650574,18,assenede bassevelde bouchaute boekhoute oost-e...,assenede
19-650636,650636,19,bridge,
20-650636,650636,20,britch,
21-650644,650644,21,dendermonde,dendermonde
22-650707,650707,22,rommel,
23-650707,650707,23,rommel charles,
...,...,...,...,...
83823-3248245,3248245,83823,café restaurant,
83824-3248245,3248245,83824,café-restaurant,
83825-3248245,3248245,83825,henseval,
83828-3248346,3248346,83828,drame de braconnage,
83829-3248346,3248346,83829,stroopersdrama,
83830-3248346,3248346,83830,wildstroopersdrama,
83831-3248370,3248370,83831,aernouts,
83833-3248416,3248416,83833,charles tuytens,
83834-3248416,3248416,83834,comptoir commercial et industriel,
83835-3248416,3248416,83835,thuysbaert-de ridder,
83836-3248416,3248416,83836,tuytens,
83832-3248416,3248416,83832,arnaud dreyfus,
83839-3248444,3248444,83839,h. col,
83838-3248444,3248444,83838,café-restaurant,
83837-3248444,3248444,83837,"6, rue de la station",
83840-3248446,3248446,83840,guy stephan,
83842-3248467,3248467,83842,"stade, louvain, louvaniste,leuven,",louvain
83841-3248467,3248467,83841,"stade, louvain, louvaniste, football, sports, ...",louvain
83841-3248467,3248467,83841,"stade, louvain, louvaniste, football, sports, ...",leuven
83843-3248474,3248474,83843,rassenfosse-brouet,
83844-3248474,3248474,83844,serrurier-bovy,
83845-3248490,3248490,83845,horrue,
83846-3248865,3248865,83846,neder over hembeek,
83847-3248955,3248955,83847,arved poorten,
83848-3248955,3248955,83848,arwed poorten,
83849-3248955,3248955,83849,edouard jacobs,
83850-3248955,3248955,83850,edouard jacobs violoncelliste,
83851-3248955,3248955,83851,poorten violoncelliste,
83852-3248976,3248976,83852,de nave,
83853-3248976,3248976,83853,tuytens,

extract_geonames = pd.DataFrame(annot['extract_lieux_be'].dropna().unique(), columns = ["name"])

geonames = extract_geonames.merge(geo, left_on='name', right_on='lower', how='left')

In [10]:
annot_geo = pd.merge(annot, geo, left_on="extract_lieux_be", right_on="lower", how="left")
annot_geo

,visitID,Column,queries,extract_lieux_be,nom_original,noms_unifie,lower
0,649635,0,london diamond,,NaN,NaN,NaN
1,649635,1,london diamond-workers,,NaN,NaN,NaN
2,649635,2,london diamond-workers trade union,,NaN,NaN,NaN
3,649756,3,bioscope,,NaN,NaN,NaN
4,649756,4,cinéma,,NaN,NaN,NaN
5,649756,5,cinématographe,,NaN,NaN,NaN
6,649756,6,cinématographie,,NaN,NaN,NaN
7,649756,7,cinématographique,,NaN,NaN,NaN
8,649858,8,soucoupes volantes,,NaN,NaN,NaN
9,649940,9,delbecq guignies,guignies,Guignies,Guignies,guignies
10,649981,10,cambron,,NaN,NaN,NaN
11,649981,11,coinne,,NaN,NaN,NaN
12,649981,12,coisne,,NaN,NaN,NaN
13,649981,13,pruvost,,NaN,NaN,NaN
14,650099,14,dendermonde,dendermonde,DENDERMONDE,Dendermonde,dendermonde
15,650099,14,dendermonde,dendermonde,DENDERMONDE,dendermonde,dendermonde
16,650099,14,dendermonde,dendermonde,DENDERMONDE,DENDERMONDE,dendermonde
17,650298,15,dendermonde,dendermonde,DENDERMONDE,Dendermonde,dendermonde
18,650298,15,dendermonde,dendermonde,DENDERMONDE,dendermonde,dendermonde
19,650298,15,dendermonde,dendermonde,DENDERMONDE,DENDERMONDE,dendermonde
20,650480,16,oud-strijder,,NaN,NaN,NaN
21,650574,17,assenede bassevelde boekhoute bouchaute oost-e...,bassevelde,Bassevelde,Bassevelde,bassevelde
22,650574,17,assenede bassevelde boekhoute bouchaute oost-e...,boekhoute,Boekhout,Boekhoute,boekhoute
23,650574,17,assenede bassevelde boekhoute bouchaute oost-e...,oost-eecloo,Oosteeklo,Oost-Eecloo,oost-eecloo
24,650574,17,assenede bassevelde boekhoute bouchaute oost-e...,assenede,ASSENEDE,Assenede,assenede
25,650574,17,assenede bassevelde boekhoute bouchaute oost-e...,assenede,ASSENEDE,ASSENEDE,assenede
26,650574,18,assenede bassevelde bouchaute boekhoute oost-e...,bassevelde,Bassevelde,Bassevelde,bassevelde
27,650574,18,assenede bassevelde bouchaute boekhoute oost-e...,boekhoute,Boekhout,Boekhoute,boekhoute
28,650574,18,assenede bassevelde bouchaute boekhoute oost-e...,oost-eecloo,Oosteeklo,Oost-Eecloo,oost-eecloo
29,650574,18,assenede bassevelde bouchaute boekhoute oost-e...,assenede,ASSENEDE,Assenede,assenede
...,...,...,...,...,...,...,...
90751,3248245,83824,café-restaurant,,NaN,NaN,NaN
90752,3248245,83825,henseval,,NaN,NaN,NaN
90753,3248346,83828,drame de braconnage,,NaN,NaN,NaN
90754,3248346,83829,stroopersdrama,,NaN,NaN,NaN
90755,3248346,83830,wildstroopersdrama,,NaN,NaN,NaN
90756,3248370,83831,aernouts,,NaN,NaN,NaN
90757,3248416,83833,charles tuytens,,NaN,NaN,NaN
90758,3248416,83834,comptoir commercial et industriel,,NaN,NaN,NaN
90759,3248416,83835,thuysbaert-de ridder,,NaN,NaN,NaN
90760,3248416,83836,tuytens,,NaN,NaN,NaN
90761,3248416,83832,arnaud dreyfus,,NaN,NaN,NaN
90762,3248444,83839,h. col,,NaN,NaN,NaN
90763,3248444,83838,café-restaurant,,NaN,NaN,NaN
90764,3248444,83837,"6, rue de la station",,NaN,NaN,NaN
90765,3248446,83840,guy stephan,,NaN,NaN,NaN
90766,3248467,83842,"stade, louvain, louvaniste,leuven,",louvain,LEUVEN,Louvain,louvain
90767,3248467,83841,"stade, louvain, louvaniste, football, sports, ...",louvain,LEUVEN,Louvain,louvain
90768,3248467,83841,"stade, louvain, louvaniste, football, sports, ...",leuven,LEUVEN,LEUVEN,leuven
90769,3248467,83841,"stade, louvain, louvaniste, football, sports, ...",leuven,LEUVEN,Leuven,leuven
90770,3248474,83843,rassenfosse-brouet,,NaN,NaN,NaN
90771,3248474,83844,serrurier-bovy,,NaN,NaN,NaN
90772,3248490,83845,horrue,,NaN,NaN,NaN
90773,3248865,83846,neder over hembeek,,NaN,NaN,NaN
90774,3248955,83847,arved poorten,,NaN,NaN,NaN
90775,3248955,83848,arwed poorten,,NaN,NaN,NaN
90776,3248955,83849,edouard jacobs,,NaN,NaN,NaN
90777,3248955,83850,edouard jacobs violoncelliste,,NaN,NaN,NaN
90778,3248955,83851,poorten violoncelliste,,NaN,NaN,NaN
90779,3248976,83852,de nave,,NaN,NaN,NaN
90780,3248976,83853,tuytens,,NaN,NaN,NaN

In [ ]:
#PROBLEME !
#df_merged = pd.merge(annot_geo, communes_complet.drop_duplicates(['noms_unifie']), left_on="nom_original", right_on="nom_original", how="left")
#df_merged

In [14]:
patronymes_locaux = []
annot['extract_persons'] = annot['queries'].apply(lambda x: get_personnes_clean(x, prenoms, lieux_be))
seen = set()
seen_add = seen.add
patronymes_locaux = [x.lower() for x in patronymes_locaux if not (x in seen or seen_add(x)) and x is not '']

In [15]:
patronymes_locaux.sort()
patronymes_locaux

[]

In [10]:
annot['extract_family'] = annot['queries'].apply(lambda x: get_family_name(x, prenoms, noms_famille, lieux_be))

In [16]:
extract_persons = pd.DataFrame(annot['extract_persons'].dropna().unique(), columns = ["persons_names"])
extract_persons

                        persons_names
0                      Diamond London
1
2                      Rommel Charles
3                      Michel Pruvost
4                   Bernard Israelite
5                        Bridge Whist
6                     Daniel De Lange
7                   Wilhelmine Clauss
8                    Amalia Rodrigues
9                        Gillet Amour
10                   Gillet Lamouline
11                 Felix Van De Weghe
12                       Anna Nellens
13                      Marcel Dupuis
14                   Victor Guillemin
15    Victor Guillemin Albert Gombert
16                  Beernaert Wilmart
17                       Gulden Valse
18                     Pierre Willems
19          Pierre Willems Professeur
20                     Pieter Willems
21                    Denis Jacquemin
22                      Albert Panier
23                         Jean Bahut
24                       Andre Boelen
25                       Gaston Block
26                     Mendes Catulle
27                      Vincent Lebbe
28                     Stevens Smeers
29                   Stevens Stacquet
...                               ...
9021                   Bernhard Meyer
9022                  Meyer Africains
9023                 Rochel Africains
9024                 Rochel Spectacle
9025                     Meyer Wahehe
9026                       Marc Sleen
9027                  Rodolphe Tppfer
9028                Willy Vandersteen
9029                   Frans Lenaerts
9030                   Charles Miller
9031                         Paul Bor
9032                      Paul Dangla
9033                   Denijs Balcaen
9034                Denijs Vandevenne
9035                       Ali Autome
9036                    Batiste Royal
9037                    Eugenio Bruni
9038                   Arnaud Dreyfus
9039                   Eleonore Gomez
9040                   Francois Gomez
9041                    Jacques Gomez
9042                 Leontine Lefevre
9043                   Marie Leclercq
9044          Marie Therese Desomberg
9045                     Henry Krauss
9046                    Martin Robyns
9047                  Charles Tuytens
9048                      Guy Stephan
9049                   Edouard Jacobs
9050    Edouard Jacobs Violoncelliste

[9051 rows x 1 columns]

start_time = time.time()
extract_persons['wikipedia_person'] = extract_persons['persons_names'].apply(lambda x: get_wikipedia(x) if len(x)> 1 else None)
print("--- %s seconds ---" % (time.time() - start_time))

start_time = time.time()
extract_persons['wikipedia_person'] = extract_persons['persons_names'].apply(lambda x: get_wikipedia(x) if len(x)> 1 else None)
print("--- %s seconds ---" % (time.time() - start_time))

In [ ]:
annot_geo

In [ ]:
annot

In [12]:
start_time = time.time()
extract_persons['isName'] = extract_persons['persons_names'].apply(lambda x: compare_names(x, noms_famille, liste_mots) if len(x)> 1 else None)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.023016691207885742 seconds ---

In [ ]:
start_time = time.time()
extract_persons['wikipedia_search'] = extract_persons['persons_names'].apply(lambda x: search_wikipedia(x) if len(x)> 1 else None)
print("--- %s seconds ---" % (time.time() - start_time))

In [12]:
extract_persons

NameError: name 'extract_persons' is not defined

In [17]:
extract_persons.to_csv(r"extract_persons.csv", encoding='utf8')

In [13]:
annot.to_csv(r"annot.csv", encoding='utf8')